[Icon Theme]
Name=SuperIcons3DWorld
Comment=My custom 3D rendered icons for GNOME. Based off the Adwaita icons pack but NOT officially endorsed!
Directories=1024x1024/apps,512x512/apps,256x256/apps,128x128/apps,64x64/apps,32x32/apps,16x16/apps

[1024x1024/apps]
Size=1024
Context=Applications
Type=Threshold

[512x512/apps]
Size=512
Context=Applications
Type=Threshold

[256x256/apps]
Size=256
Context=Applications
Type=Threshold

[128x128/apps]
Size=128
Context=Applications
Type=Threshold

[64x64/apps]
Size=64
Context=Applications
Type=Threshold

[32x32/apps]
Size=32
Context=Applications
Type=Threshold

[16x16/apps]
Size=16
Context=Applications
Type=Threshold
